
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@10.226.40.23:8761/eureka/

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: luckystar
    password: 1qazZAQ!