# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.tfc.luckystar: DEBUG
    org.springframework.web.client.RestTemplate: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: luckystar
    password: luckystar
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: ORACLE
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: luckystar
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-683405.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa1w9igd9EVTN7uv357 
            client-secret: ss1MYwYSj3tIYRN63MHMc7wY7eegU1sYBp_w0-_U

server:
  port: 8081

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
      management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
        enabled: false
        update-interval: 3
        url: http://localhost:8180/mancenter
  # CORS is disabled by default on microservices, as you should access them through a gateway.
  # If you want to enable it, please uncomment the configuration below.
  # cors:
  #     allowed-origins: "*"
  #     allowed-methods: "*"
  #     allowed-headers: "*"
  #     exposed-headers: "Authorization,Link,X-Total-Count"
  #     allow-credentials: true
  #     max-age: 1800
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8081
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

tfc:
  luckystar:
    smsgw:
      shortcode: 777
      alias: 777
      url: http://10.226.46.48:9201/smsws?wsdl
      username: 777u
      password: 777p
    ws:
      username: TFC2019u
      password: TFC2019p
      # mps_key_dir: /Users/cuongtd/TFC/docs/luckydraw/key_add
    sms:
      mtScheduler:
        active: false
        fixedRate-in-milliseconds: 5000
        limitRow: 50
    modbalance:
      serviceId: LUCKYSTAR_MODBALANCE
      mps_key_dir: /Users/cuongtd/TFC/key/LUCKYSTAR_MODBALANCE
      service: LUCKYSTAR
      subService: LUCKYSTAR_MODBALANCE
      url: http://10.226.46.22:9181/MPS/charge.html?
      url-params:
        pro: TFC
        ser: LUCKYSTAR
        sub: LUCKYSTAR_MODBALANCE
        cmd: MODBALANCEM
      data-params:
      command: MODBALANCEM
      proCode: 
    lottery:
      msg:
        help: Test - This is help message
        check: Test - This is check message
        getDe: "Dream Entertainment Lottery on {drawdate}: {result}. Resultadu ba referensia."
        getFt: "FITUN Lottery on {drawdate}: {result}. Resultadu ba referensia."
        wrongcmd: Wrong command!
      de:
        serviceId: LUCKYSTAR_DE
        draw-time: "11:30:00"
        resultScheduler:
          active: false
          fixedRate-in-milliseconds: 15000
          limitRow: 50
        phone.approve: "75511095"
        phone.notification: "75511095"
        sms_template: "Dream Entertainment Lottery on {drawdate}: \n{result}. \nResultadu ba referensia."
        sms_no_result_today: "No result today yet. Please try later."
      ft:
        serviceId: LUCKYSTAR_FT
        draw-time: "21:30:00"
        resultScheduler:
          active: false
          fixedRate-in-milliseconds: 15000
          limitRow: 50
        sms_template: "Fitun Lottery on {drawdate}: \n{result}. \nResultadu ba referensia."
        sms_no_result_today: "No result today yet. Please try later."
      betting:
        serviceId: LUCKYSTAR_BETTING
        mps_key_dir: /u01/app/luckystar/key/LUCKYSTAR_BETTING
        bet_before_hour: 20
        wrong_syntax_message: "Deskulpa, Sintaxe loos mak: KISS XX. Numeru XX mak numeru dijitu rua neebe ita aposta. Favor koko fali!"
        over_time_message: "Oras aposta hahu 00:00 ba 20:00 lor-loron, favor koko hikas tempu seluk. Obrigadu!"
        bet_success_message: "Aposta ho susesu. Ita aposta ona 10cent ba numeru {number} lotaria KISS (DE) iha loron {drawdate}. bele manan liu $3. Ami sei informa bainhira rezultadu disponivel. Boa Sorte."
        win_amount_1: 300
        win_message_1: "Parabens, ita manan {winamount} ba numeru aposta {number} ho premiu bola primeiru lotaria KISS iha {drawdate}. Hatan DE (20cent/tempu) ka ON DE (10cent/loron) hodi haree rezultadu."
        win_amount_2: 30
        win_message_2: "Parabens, ita manan {winamount} ba numeru aposta {number} dala {wintimes} ho lotaria KISS iha {drawdate}. Hatan DE (20cent/tempu) ka ON DE (10cent/loron) hodi haree rezultadu."
        lose_message: "Ita nia numeru aposta {number} la par ho kualker rezultadu husi lotaria KISS loron {drawdate}."
        scheduler:
          active: true
          check_after_hour: 18
          check_after_minute: 0
          check_after_draw_minute: 30
          fixedRate-in-milliseconds: 50000
          limitRow: 10
      smstpl:
        lucknumbersms: "{luckynumber} is your lucky number. Good luck!"
    news:
      sportnews:
        serviceId: LUCKYSTAR_SPORTNEWS
        scheduler:
          active: false
          fixedRate-in-milliseconds: 45000
          limitRow: 50
      starnews:
        serviceId: LUCKYSTAR_STARNEWS
        scheduler:
          active: false
          fixedRate-in-milliseconds: 45000
          limitRow: 50
      hundredYearsAgo:
        serviceId: LUCKYSTAR_100YEARSAGO
        scheduler:
          active: false
          fixedRate-in-milliseconds: 45000
          limitRow: 50
      healthnews:
        serviceId: LUCKYSTAR_HEALTHNEWS
        scheduler:
          active: false
          fixedRate-in-milliseconds: 15000
          limitRow: 50