# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  file: log/luckystar.log
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    com.tfc.luckystar: INFO
    org.springframework.ws.server.MessageTracing.sent: INFO
    org.springframework.ws.server.MessageTracing.received: INFO
    org.springframework.ws.client.MessageTracing.sent: INFO
    org.springframework.ws.client.MessageTracing.received: INFO
    com.tfc.luckystar.ScheduledTaskBet: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instanceId: luckystar:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@eureka-peer-1:8761/eureka/,http://admin:${jhipster.registry.password}@eureka-peer-2:8761/eureka/

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=yes)(ADDRESS=(PROTOCOL=TCP)(HOST=10.226.45.64)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.226.45.74)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=tmovas)))
    username: luckystar
    password: 12at5yKcu7
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      # modify fetch size as necessary
      hibernate.jdbc.fetch_size: 150
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: luckystar
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
  liquibase:
    enabled: false
    contexts: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: thetfcltd@gmail.com
    password: T1qazZAQ!
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  thymeleaf:
    cache: true
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-683405.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa1w9igd9EVTN7uv357 
            client-secret: ss1MYwYSj3tIYRN63MHMc7wY7eegU1sYBp_w0-_U

# ===================================================================
# To enable TLS in production, generate a certificate using:
# keytool -genkey -alias luckystar -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: luckystar
#        # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#        ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
      management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
        enabled: false
        update-interval: 3
        url:
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://my-server-url-to-change # Modify according to your server's URL
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

tfc:
  luckystar:
    smsgw:
      shortcode: 777
      alias: 777
      url: http://10.226.46.48:9201/smsws?wsdl
      username: 777u
      password: 777p
    ws:
      username: TFC2019u
      password: TFC2019p
      # mps_key_dir: /Users/cuongtd/TFC/docs/luckydraw/key_add
    sms:
      mtScheduler:
        active: true
        fixedRate-in-milliseconds: 5000
        limitRow: 25
    modbalance:
      serviceId: LUCKYSTAR_MODBALANCE
      mps_key_dir: /u01/app/luckystar/key/LUCKYSTAR_MODBALANCE
      service: LUCKYSTAR
      subService: LUCKYSTAR_MODBALANCE
      url: http://10.226.46.22:9181/MPS/charge.html?
      url-params:
        pro: TFC
        ser: LUCKYSTAR
        sub: LUCKYSTAR_MODBALANCE
        cmd: MODBALANCEM
      data-params:
      command: MODBALANCEM
      proCode: 
    lottery:
      msg:
        help: Test - This is help message
        check: Test - This is check message
        getDe: "Dream Entertainment Lottery on {drawdate}: {result}. Resultadu ba referensia."
        getFt: "FITUN Lottery on {drawdate}: {result}. Resultadu ba referensia."
        wrongcmd: Wrong command!
      de:
        serviceId: LUCKYSTAR_DE
        draw-time: "21:30:00"
        resultScheduler:
          active: true
          fixedRate-in-milliseconds: 10000
          limitRow: 25
        phone.approve: "75511095"
        phone.notification: "75511095"
        sms_template: "Dream Entertainment Lottery on {drawdate}: \n{result}. \nResultadu ba referensia."
        sms_no_result_today: "Rezultadu seidauk iha. Favor koko oras tan. \nNo result today yet. Please try later."
      ft:
        serviceId: LUCKYSTAR_FT
        draw-time: "21:30:00"
        resultScheduler:
          active: false
          fixedRate-in-milliseconds: 10000
          limitRow: 25
        sms_template: "Fitun Lottery on {drawdate}: \n{result}. \nResultadu ba referensia."
        sms_no_result_today: "Rezultadu seidauk iha. Favor koko oras tan. \nNo result today yet. Please try later."
      betting:
        serviceId: LUCKYSTAR_BETTING
        mps_key_dir: /u01/app/luckystar/key/LUCKYSTAR_MODBALANCE
        bet_before_hour: 20
        wrong_syntax_message: "Deskulpa, Sintaxe loos mak: KISS XX. Numeru XX mak numeru dijitu rua neebe ita aposta. Favor koko fali!"
        over_time_message: "Oras aposta hahu 00:00 ba 20:00 lor-loron, favor koko hikas tempu seluk. Obrigadu!"
        bet_success_message: "Aposta ho susesu. Ita aposta ona 10cent ba numeru {number} lotaria KISS (DE) iha loron {drawdate}. bele manan liu $3. Ami sei informa bainhira rezultadu disponivel. Boa Sorte."
        win_amount_1: 300
        win_message_1: "Parabens, ita manan {winamount} ba numeru aposta {number} ho premiu bola primeiru lotaria KISS iha {drawdate}. Hatan DE (20cent/tempu) ka ON DE (10cent/loron) hodi haree rezultadu."
        win_amount_2: 30
        win_message_2: "Parabens, ita manan {winamount} ba numeru aposta {number} dala {wintimes} ho lotaria KISS iha {drawdate}. Hatan DE (20cent/tempu) ka ON DE (10cent/loron) hodi haree rezultadu."
        lose_message: "Ita nia numeru aposta {number} la par ho kualker rezultadu husi lotaria KISS loron {drawdate}."
        scheduler:
          active: true
          check_after_hour: 21
          check_after_minute: 30
          check_after_draw_minute: 15
          fixedRate-in-milliseconds: 2000
          limitRow: 1
      smstpl:
        lucknumbersms: "{luckynumber} is your lucky number. Good luck!"
    news:
      sportnews:
        serviceId: LUCKYSTAR_SPORTNEWS
        scheduler:
          active: true
          fixedRate-in-milliseconds: 30000
          limitRow: 25
      starnews:
        serviceId: LUCKYSTAR_STARNEWS
        scheduler:
          active: true
          fixedRate-in-milliseconds: 30000
          limitRow: 25
      hundredYearsAgo:
        serviceId: LUCKYSTAR_100YEARSAGO
        scheduler:
          active: true
          fixedRate-in-milliseconds: 30000
          limitRow: 25
      healthnews:
        serviceId: LUCKYSTAR_HEALTHNEWS
        scheduler:
          active: true
          fixedRate-in-milliseconds: 30000
          limitRow: 25