spring:
  security:
    user:
      name: admin
      password: T1qazZAQ!
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-683405.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa1xiepe4VoCcTAu357
            client-secret: nKfwTTsexp3JORpPZ2BGyh3jUMsMHboXQ2dZ9EVK
logging:
    file: log/jhipster-registry.log